### ISSUE TITLE
Possible PR

### ISSUE THREAD

**Issue by philipturner** [Po-Jen/awesome-3d-multi-object-tracking#1]
I have a research paper on [adding color to scene reconstruction](https://github.com/philipturner/scene-color-reconstruction) that just got rejected from openMVG/awesome_3DReconstruction_list. Would mine qualify for this repository? It may be a bit off-topic, so I'm not making a PR yet.

**Comment by Po-Jen** [comment]
Thanks for asking. I don't think it's related, so I am closing this issue. If you have anything that's related to multi-object tracker, feel free to open an issue or PR :)

**Comment by philipturner** [comment]
Wow. This was made a LOOOONG time ago. So much has changed since then. I might have closed this PR myself if I had known about it!
